[build]
  command = "yarn build"
  publish = "dist"
  functions = "server/functions"

[[redirects]]
  from = "/api/portfolio"
  to = "/.netlify/functions/portfolio"
  status = 200

[[redirects]]
  from = "/api/resume"
  to = "/.netlify/functions/resume"
  status = 200

[[redirects]]
  from = "/api/send-email"
  to = "/.netlify/functions/send-email"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
